mutation assignProjectToUser($where: UserWhere, $connect: UserConnectInput) {
  updateUsers(where: $where, connect: $connect) {
    users {
      emailId
      hasProjects {
        id
        name
      }
    }
  }
}
