query getFilesAndFoldersByProjectId($where: ProjectWhere) {
  projects(where: $where) {
    id
    name
    isOpen
    hasContainsFolder {
      id
      isOpen
      name
      type
      hasFile {
        id
        name
        type
      }
    }
    hasContainsFile {
      id
      type
      name
    }
  }
}
