mutation deleteLink(
  $where: FlowNodeWhere
  $disconnect: FlowNodeDisconnectInput
) {
  updateFlowNodes(where: $where, disconnect: $disconnect) {
    flowNodes {
      id
      label
      isLinked {
        label
      }
    }
  }
}
